security:
    providers:
        app_user_provider:
            entity:
                class: App\User\Domain\Entity\User
                property: login

    firewalls:
        main:
            security: false

    password_hashers:
        App\User\Domain\Entity\User:
            algorithm: auto
            cost: 15

when@dev:
    security:
        providers:
            app_user_provider:
                entity:
                    class: App\User\Domain\Entity\User
                    property: login

        firewalls:
            main:
                security: false

        password_hashers:
            App\User\Domain\Entity\User:
                algorithm: auto
                cost: 4

when@test:
    security:
        providers:
            app_user_provider:
                entity:
                    class: App\User\Domain\Entity\User
                    property: login

        firewalls:
            main:
                security: false

        password_hashers:
            App\User\Domain\Entity\User:
                algorithm: auto
                cost: 4