services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "8000:80"
    volumes:
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_IDE_CONFIG=serverName=API
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/schema
    environment:
      - SWAGGER_JSON=/schema/swagger.json
      - BASE_URL=/swagger

volumes:
  mysql_data:
